//! Project-specific FFI declarations for our @[export] Lean functions.

use lean_sys::{lean_obj_arg, lean_obj_res};

unsafe extern "C" {
    // Module initializer (generated by Lean compiler)
    pub fn initialize_arith__circuit_ArithCircuit(builtin: u8) -> lean_obj_res;

    // Expr constructors
    pub fn arith_expr_const(n: lean_obj_arg) -> lean_obj_res;
    pub fn arith_expr_var(i: lean_obj_arg) -> lean_obj_res;
    pub fn arith_expr_add(a: lean_obj_arg, b: lean_obj_arg) -> lean_obj_res;
    pub fn arith_expr_mul(a: lean_obj_arg, b: lean_obj_arg) -> lean_obj_res;

    // Core operations
    pub fn arith_expr_simplify(e: lean_obj_arg) -> lean_obj_res;
    pub fn arith_expr_eval(env: lean_obj_arg, e: lean_obj_arg) -> lean_obj_res;
    pub fn arith_expr_eval_fn(env: lean_obj_arg, e: lean_obj_arg) -> lean_obj_res;
    pub fn arith_expr_to_string(e: lean_obj_arg) -> lean_obj_res;

    // Array builder
    pub fn arith_array_push(a: lean_obj_arg, v: lean_obj_arg) -> lean_obj_res;

    // Closure shim (compiled against the real lean.h)
    pub fn shim_alloc_closure(
        fun: *mut std::ffi::c_void,
        arity: std::ffi::c_uint,
        num_fixed: std::ffi::c_uint,
    ) -> lean_obj_res;
}
