//! Raw FFI declarations for the Lean runtime and our exported functions.

#![allow(dead_code)]

use std::ffi::c_void;

// Opaque Lean object pointer
pub type LeanObj = *mut c_void;

unsafe extern "C" {
    // ── Lean runtime lifecycle ───────────────────────────────────
    pub fn lean_initialize_runtime_module();
    pub fn lean_initialize_thread();
    pub fn lean_io_mark_end_initialization();
    pub fn lean_set_panic_messages(enabled: u8);

    // ── Module initializer (generated by Lean compiler) ──────────
    pub fn initialize_arith__circuit_ArithCircuit(builtin: u8) -> LeanObj;

    // ── Our @[export] functions ──────────────────────────────────
    pub fn arith_expr_const(n: LeanObj) -> LeanObj;
    pub fn arith_expr_var(i: LeanObj) -> LeanObj;
    pub fn arith_expr_add(a: LeanObj, b: LeanObj) -> LeanObj;
    pub fn arith_expr_mul(a: LeanObj, b: LeanObj) -> LeanObj;
    pub fn arith_expr_simplify(e: LeanObj) -> LeanObj;
    pub fn arith_expr_eval(env: LeanObj, e: LeanObj) -> LeanObj;
    pub fn arith_expr_eval_fn(env: LeanObj, e: LeanObj) -> LeanObj;
    pub fn arith_expr_to_string(e: LeanObj) -> LeanObj;
    pub fn arith_array_push(a: LeanObj, v: LeanObj) -> LeanObj;

    // ── C shim wrappers (for static-inline Lean functions) ───────
    pub fn shim_inc(o: LeanObj);
    pub fn shim_dec(o: LeanObj);
    pub fn shim_box(n: usize) -> LeanObj;
    pub fn shim_unbox(o: LeanObj) -> usize;
    pub fn shim_is_scalar(o: LeanObj) -> i32;
    pub fn shim_int64_to_int(n: i64) -> LeanObj;
    pub fn shim_scalar_to_int64(o: LeanObj) -> i64;
    pub fn shim_unsigned_to_nat(n: u32) -> LeanObj;
    pub fn shim_string_cstr(o: LeanObj) -> *const i8;
    pub fn shim_io_mk_world() -> LeanObj;
    pub fn shim_io_result_is_ok(r: LeanObj) -> i32;
    pub fn shim_mk_empty_array() -> LeanObj;

    // ── Closure support (for function-pointer eval) ──────────────
    pub fn shim_set_env_callback(cb: Option<unsafe extern "C" fn(usize) -> i64>);
    pub fn shim_make_env_closure() -> LeanObj;
}
